In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [12]:
price=pd.read_csv("Price.csv")
price.head()

,ProductID,ProductName,Brand,Category_Level_0,Category_Level_1,Category_Level_2,Category_Level_3,Fiyat
0,1.0,Fairy Platinum Tablet,Fairy,Deterjan,Bulaşık Yıkama,Bulaşık Makinesi Ürünleri,Tablet Deterjanlar,60
1,2.0,Komili Riviera Yağı,Komili,"Gıda, Şekerleme",Sıvı Yağlar,Zeytinyağı,Riviera Zeytinyağı,40
2,3.0,Marmara Birlik Siyah Zeytin,Marmara Birlik,"Süt, Kahvaltılık",Zeytin,Siyah Zeytin,Özel Siyah Zeytin,20
3,4.0,CityFarm Organik 10'lu Yumurta,City Farm,"Süt, Kahvaltılık",Yumurta,Özel Yumurta,Özel Yumurta,20
4,5.0,Sütaş Pastörize Süt,Sütaş,"Süt, Kahvaltılık",Süt,Pastörize Süt,Pastörize Sade Süt,5

In [5]:
invoice=pd.read_csv("Invoice.csv")
invoice.head()

   Invoice ID Invoice Date   Invoice_Total Payment Method
0           1    23.03.2019            150          Debit
1           2    23.03.2019             65    Credit Card
2           3    23.03.2019            140          Debit
3           4    23.03.2019             75    Credit Card
4           5    23.03.2019             55    Credit Card

In [6]:
invoice_details=pd.read_csv("InvoiceDetails.csv")
invoice_details.head()

   InvoiceDetailID  InvoiceID  ProductID  Total  Adet
0                1          1          1     60   1.0
1                2          1          7     50   2.0
2                3          1          2     40   1.0
3                4          2          2     40   1.0
4                5          2          4     20   1.0

In [28]:
price_new = price.drop(['Brand','Category_Level_0','Category_Level_1','Category_Level_2','Category_Level_3','Fiyat'],axis=1)

In [29]:
price_new.head()

   ProductID                     ProductName
0        1.0           Fairy Platinum Tablet
1        2.0             Komili Riviera Yağı
2        3.0     Marmara Birlik Siyah Zeytin
3        4.0  CityFarm Organik 10'lu Yumurta
4        5.0             Sütaş Pastörize Süt

In [30]:
df = pd.merge(invoice_details,price_new,on='ProductID')

In [31]:
df.head()

   InvoiceDetailID  InvoiceID  ProductID  Total  Adet            ProductName
0                1          1          1     60   1.0  Fairy Platinum Tablet
1                7          3          1     60   1.0  Fairy Platinum Tablet
2               24          8          1     60   2.0  Fairy Platinum Tablet
3               35         12          1     60   3.0  Fairy Platinum Tablet
4               54         19          1     60   1.0  Fairy Platinum Tablet

In [38]:
basket = (df.groupby(['InvoiceID', 'ProductName'])['Adet']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceID'))

In [40]:
basket.head()

ProductName,Beypazarı Maden Suyu 6X200 Ml,Bonne Maman Çilek Reçeli 370 G,CityFarm Organik 10'lu Yumurta,Coca-Cola Şekersiz 6X250ML Kutu,Doğuş Toz Şeker 1 Kg,Elma Fuji Kg,Fairy Platinum Tablet,Komili Riviera Yağı,Limon Nostalji File Kg,Marmara Birlik Siyah Zeytin,...,Nutella 750 G,Prima Premium Care İkiz Paket 5 No Junior 25'Li,Selpak Lavanta Tuvalet Kağıdı 32'li,Sütaş Pastörize Süt,Sütaş Tava Yoğurt 1000 G,Torku Tereyağ 500 G,Yayla Dermason Fasulye 1 Kg,Yayla Koçbaşı Nohut 1000 G,Yayla Kırmızı Mercimek 1 Kg,Çilek Kg
InvoiceID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,3.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
def encode_unit(x):
    if x<=0:
        return 0
    if x>=1:
        return 1

In [44]:
set_basket = basket.applymap(encode_unit)
set_basket.head()

ProductName,Beypazarı Maden Suyu 6X200 Ml,Bonne Maman Çilek Reçeli 370 G,CityFarm Organik 10'lu Yumurta,Coca-Cola Şekersiz 6X250ML Kutu,Doğuş Toz Şeker 1 Kg,Elma Fuji Kg,Fairy Platinum Tablet,Komili Riviera Yağı,Limon Nostalji File Kg,Marmara Birlik Siyah Zeytin,...,Nutella 750 G,Prima Premium Care İkiz Paket 5 No Junior 25'Li,Selpak Lavanta Tuvalet Kağıdı 32'li,Sütaş Pastörize Süt,Sütaş Tava Yoğurt 1000 G,Torku Tereyağ 500 G,Yayla Dermason Fasulye 1 Kg,Yayla Koçbaşı Nohut 1000 G,Yayla Kırmızı Mercimek 1 Kg,Çilek Kg
InvoiceID,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,1,1,0,1,...,1,0,0,0,0,0,0,0,0,0
4,1,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,0,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

# set parameters for apriori algorithms

In [46]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [49]:
frequent_items = apriori(set_basket, min_support=0.15,use_colnames=True)
frequent_items

    support                                           itemsets
0      0.26                    (Beypazarı Maden Suyu 6X200 Ml)
1      0.32                   (CityFarm Organik 10'lu Yumurta)
2      0.24                                     (Elma Fuji Kg)
3      0.30                            (Fairy Platinum Tablet)
4      0.34                              (Komili Riviera Yağı)
5      0.32                      (Marmara Birlik Siyah Zeytin)
6      0.16                                    (Nutella 750 G)
7      0.20  (Prima Premium Care İkiz Paket 5 No Junior 25'Li)
8      0.24              (Selpak Lavanta Tuvalet Kağıdı 32'li)
9      0.16                         (Sütaş Tava Yoğurt 1000 G)
10     0.18                                         (Çilek Kg)
11     0.16  (Fairy Platinum Tablet, Marmara Birlik Siyah Z...
12     0.16  (Marmara Birlik Siyah Zeytin, Komili Riviera Y...